# HARP: 36.3703 -122.3148
# MARS: 36.712465 -122.187548
SENSOR_LAT = 36.3703
SENSOR_LON = -122.3148
DETECT_ZONE = 0
BUFFER_ZONE = 1
NOSHIP_ZONE = 2
NOSHIP_LABEL = "Class F"
NOSHIP_MMSI = "NOSHIP"

def get_desig_class(desig):
    '''
    Description: returns the class according to the ship designation
    :desig:
    '''
    if desig in SHIP_CLASS:
        return SHIP_CLASS[desig]
    else:
        return NOSHIP_LABEL
    
SHIP_CLASS = {
    # Class A
    'Mooring Vessel':'Class A',
    'Fire Fighting Vessel':'Class A',
    'Work/Repair Vessel':'Class A',
    'Search & Rescue Vessel':'Class A',
    'Waste Disposal Vessel':'Class A',
    'WIG (HAZ-B)':'Class A',
    'WIG (HAZ-A)':'Class A',
    'WIG (HAZ-C)':'Class A',
    'WIG':'Class A',
    'Medical':'Class A',
    'Anchor Hoy':'Class A',
    'Landings Craft':'Class A',
    'Military ops':'Class A',
    'Fishing vessels':'Class A',
    'Fishing vessel':'Class A',
    'Fishing Vessel':'Class A',
    'Fishing': 'Class A',
    'Fishing Support Vessel':'Class A',
    'Tug':'Class A',
    'Pusher Tug':'Class A',
    'Dredging or UW ops':'Class A',
    'Dredging or underwater ops':'Class A',
    'Towing vessel':'Class A',
    'Towing':'Class A',
    'Towing: length exceeds 200m or breadth exceeds 25m':'Class A',
    'Crew Boat':'Class A',
    'Buoy/Lighthouse Vessel':'Class A',
    'Salvage Ship':'Class A',
    'Research Vessel':'Class A',
    'Anti-polution':'Class A',
    'Anti-pollution':'Class A',
    'Offshore Tug/Supply Ship':'Class A',
    'Law enforcment':'Class A',
    'Law enforcement':'Class A',
    'Landing Craft':'Class A',
    'SAR':'Class A',
    'Search and Rescue vessel':'Class A',
    'Patrol Vessel':'Class A',
    'Port tender':'Class A',
    'Pollution Control Vessel': 'Class A',
    'Offshore Support Vessel':'Class A',
    'Towing vessel (tow>200)':'Class A',
    'Fish Carrier':'Class A',
    'Utility Vessel': 'Class A',
    'HSC':'Class A',
    'HSC (HAZ-B)':'Class A',
    'HSC (HAZ-A)':'Class A',
    'Dredger':'Class A',
    'Pilot Vessel':'Class A',
    'Crane Ship':'Class A',
    'Resolution 18 ship':'Class A',
    'Standby Safety Vessel':'Class A',
    'Local type':'Class A',
    'Spare - Local Vessel':'Class A',
    'Trawler':'Class A',
    
    # Class B
    'Pleasure Craft':'Class B',
    'Pleasure craft':'Class B',
    'Yacht':'Class B',
    'Sailing Vessel':'Class B',
    'Sailing vessel':'Class B',
    'Sailing':'Class B',
    'Pilot':'Class B',
    'Diving ops':'Class B',
    'Other type (HAZ-A)':'Class B',
    'Passenger ship (HAZ-C)':'Class B',

    # Class C
    'Passenger, all ships of this type':'Class C',
    'Passenger, Reserved for future use':'Class C',
    'Passenger, No additional information':'Class C',
    'Passenger (Cruise) Ship':'Class C',
    'Passenger Ship':'Class C',
    'Passenger ship':'Class C',
    'Passenger ship (HAZ-D)':'Class C',
    'Passenger ship (HAZ-B)':'Class C',
    'Passenger': 'Class C',
    'Passenger/General Cargo Ship':'Class C',
    'Training Ship': 'Class C',
    'Hopper Dredger':'Class C',
    'Inland Passenger':'Class C',

    # Class D
    'Naval/Naval Auxiliary':'Class D',
    'Barge Carrier':'Class D',
    'DDG':'Class D',
    'LCS':'Class D',
    'Hospital Vessel':'Class D',
    'Self Discharging Bulk Carrier':'Class D',
    'Cutter':'Class D',
    'Passenger/Ro-Ro Cargo Ship':'Class D',
    'Heavy Load Carrier':'Class D',
    'Vessel (function unknown)':'Class D',
    'General Cargo Ship':'Class D',
    'Wood Chips Carrier':'Class D',
    'Bulk Carrier':'Class D' ,
    'Cement Carrier':'Class D',
    'Unknown (HAZ-A)':'Class D',
    'Other type (HAZ-A)':'Class D',
    'Vehicles Carrier':'Class D',
    'Cargo ship (HAZ-A)':'Class D',
    'Cargo, Hazardous category A':'Class D',
    'Cargo, Hazardous category B':'Class D',
    'Cargo, Hazardous category C':'Class D',
    'Cargo, Hazardous category D':'Class D',
    'Cargo ship (HAZ-C)':'Class D',
    'Cargo ship':'Class D',
    'Cargo':'Class D',
    'Cargo, all ships of this type':'Class D',
    'Cargo, No additional information':'Class D',
    'Oil Products Tanker':'Class D',
    'Ro-Ro Cargo Ship':'Class D',
    'Ro-Ro Cargo':'Class D',
    'Fruit Juice Tanker':'Class D',
    'Bitumen Tanker':'Class D',
    'Production Testing Vessel':'Class D',
    'USNS RAINIER':'Class D',
    'Supply Tender':'Class D',
    'Cargo ship':'Class D',
    'LPG Tanker':'Class D',
    'Crude Oil Tanker':'Class D',
    'Container Ship':'Class D',
    'Container ship':'Class D',
    'Bulk Carrier':'Class D',
    'Chemical/Oil Products Tanker':'Class D',
    'Chemical Tanker':'Class D',
    'Refrigerated Cargo Ship':'Class D',
    'Tanker':'Class D',
    'Car Carrier':'Class D',
    'Deck Cargo Ship' :'Class D',
    'Livestock Carrier': 'Class D',
    'Bunkering Tanker':'Class D',
    'Water Tanker': 'Class D',
    'FSO': 'Class D',
    'Cable Layer':'Class D',
    'LNG Tanker':'Class D',
    'Motor Hopper':'Class D',
    'Icebreaker':'Class D',
    'Fish Factory Ship':'Class D',
    'Drilling Ship':'Class D',
    'Bulk/Oil Carrier':'Class D',
    'Palletised Cargo Ship':'Class D',
    'Aggregates Carrier':'Class D',
    'Pipe Layer':'Class D',
    'Pipe Burying Vessel':'Class D',
    'Power Station Vessel':'Class D',
    'Liquefied Gas':'Class D',
    'Rocket Launch Support Ship':'Class D',
    'Well Stimulation Vessel':'Class D',
    'Tanker, all ships of this type':'Class D',
    'Tanker, Hazardous category A':'Class D',
    'Tanker, Hazardous category B':'Class D',
    'Tanker, Hazardous category C':'Class D',
    'Tanker, Hazardous category D':'Class D',
    'Tanker, Reserved for future use':'Class D',
    'Tanker, No additional information':'Class D',


    # Class E
    'Other type':'Class E',
    'Other Type, no additional information':'Class E',
    'Other Type, all ships of this type': 'Class E',
    'Other Type, Hazardous category A': 'Class E',
    'Other Non Merchant Ships':'Class E',
    'Other type (HAZ-B)':'Class E',
    'Unknown (HAZ-C)':'Class E',
    'Unknown (HAZ-B)':'Class E',
    'Reserved':'Class E',
    'Not available':'Class E',
    'Not available (default)':'Class E',
    '-1':'Class E',
    'Unknown':'Class E',
    'Platform':'Class E',
    'Non Propelled Barge':'Class E'
}

VESSEL_TYPES = {
    0: 'Not available (default)',
    30: 'Fishing',
    31: 'Towing',
    32: 'Towing: length exceeds 200m or breadth exceeds 25m',
    33: 'Dredging or underwater ops',
    34: 'Diving ops',
    35: 'Military ops',
    36: 'Sailing',
    37: 'Pleasure Craft',
    38: 'Reserved',
    40: 'HSC',
    51: 'Search and Rescue vessel',
    52: 'Tug',
    53: 'Port tender',
    55: 'Law enforcement',
    57: 'Spare - Local Vessel',
    59: 'Noncombatant ship according to RR Resolution No. 18',
    60: 'Passenger, all ships of this type',
    67: 'Passenger, Reserved for future use',
    70: 'Cargo, all ships of this type',
    71: 'Cargo, Hazardous category A',
    72: 'Cargo, Hazardous category B',
    73: 'Cargo, Hazardous category C',
    74: 'Cargo, Hazardous category D',
    79: 'Cargo, No additional information',
    80: 'Tanker, all ships of this type',
    81: 'Tanker, Hazardous category A',
    82: 'Tanker, Hazardous category B',
    83: 'Tanker, Hazardous category C',
    84: 'Tanker, Hazardous category D',
    85: 'Tanker, Reserved for future use',
    89: 'Tanker, No additional information',
    90: 'Other Type, all ships of this type',
    91: 'Other Type, Hazardous category A',
    99: 'Other Type, no additional information',
}

LABEL_COMBINATIONS = [(),
 ('Class A',),
 ('Class B',),
 ('Class C',),
 ('Class D',),
 ('Class E',),
 ('Class F',),
 ('Class A', 'Class B'),
 ('Class A', 'Class C'),
 ('Class A', 'Class D'),
 ('Class A', 'Class E'),
 ('Class A', 'Class F'),
 ('Class B', 'Class C'),
 ('Class B', 'Class D'),
 ('Class B', 'Class E'),
 ('Class B', 'Class F'),
 ('Class C', 'Class D'),
 ('Class C', 'Class E'),
 ('Class C', 'Class F'),
 ('Class D', 'Class E'),
 ('Class D', 'Class F'),
 ('Class E', 'Class F'),
 ('Class A', 'Class B', 'Class C'),
 ('Class A', 'Class B', 'Class D'),
 ('Class A', 'Class B', 'Class E'),
 ('Class A', 'Class B', 'Class F'),
 ('Class A', 'Class C', 'Class D'),
 ('Class A', 'Class C', 'Class E'),
 ('Class A', 'Class C', 'Class F'),
 ('Class A', 'Class D', 'Class E'),
 ('Class A', 'Class D', 'Class F'),
 ('Class A', 'Class E', 'Class F'),
 ('Class B', 'Class C', 'Class D'),
 ('Class B', 'Class C', 'Class E'),
 ('Class B', 'Class C', 'Class F'),
 ('Class B', 'Class D', 'Class E'),
 ('Class B', 'Class D', 'Class F'),
 ('Class B', 'Class E', 'Class F'),
 ('Class C', 'Class D', 'Class E'),
 ('Class C', 'Class D', 'Class F'),
 ('Class C', 'Class E', 'Class F'),
 ('Class D', 'Class E', 'Class F'),
 ('Class A', 'Class B', 'Class C', 'Class D'),
 ('Class A', 'Class B', 'Class C', 'Class E'),
 ('Class A', 'Class B', 'Class C', 'Class F'),
 ('Class A', 'Class B', 'Class D', 'Class E'),
 ('Class A', 'Class B', 'Class D', 'Class F'),
 ('Class A', 'Class B', 'Class E', 'Class F'),
 ('Class A', 'Class C', 'Class D', 'Class E'),
 ('Class A', 'Class C', 'Class D', 'Class F'),
 ('Class A', 'Class C', 'Class E', 'Class F'),
 ('Class A', 'Class D', 'Class E', 'Class F'),
 ('Class B', 'Class C', 'Class D', 'Class E'),
 ('Class B', 'Class C', 'Class D', 'Class F'),
 ('Class B', 'Class C', 'Class E', 'Class F'),
 ('Class B', 'Class D', 'Class E', 'Class F'),
 ('Class C', 'Class D', 'Class E', 'Class F'),
 ('Class A', 'Class B', 'Class C', 'Class D', 'Class E'),
 ('Class A', 'Class B', 'Class C', 'Class D', 'Class F'),
 ('Class A', 'Class B', 'Class C', 'Class E', 'Class F'),
 ('Class A', 'Class B', 'Class D', 'Class E', 'Class F'),
 ('Class A', 'Class C', 'Class D', 'Class E', 'Class F'),
 ('Class B', 'Class C', 'Class D', 'Class E', 'Class F'),
 ('Class A', 'Class B', 'Class C', 'Class D', 'Class E', 'Class F')]